### ISSUE TITLE
TODO lista

### ISSUE THREAD

**Issue by Szaller99** [Szaller99/BRSzT-Hazi-Torpedo-Tea-Szaller-Laci#1]
Közös TODO lista, hogy lássuk, hogy ki mit csinál @Ketszersult @toratoraaa @Szaller99 :
- [x] Game
   - [x] Battleship - in progress @Ketszersult 
   - [x] Game
     - [x] eventHandling @toratoraaa @Ketszersult 
   - [x] Player
   - [x] State machine @Szaller99 
- [x] View (Design)
   - [x] design files @toratoraaa 
      - [x] field pngs
      - [x] battleship pngs  
   - [x] Basic window/frame elements @Szaller99 
   - [x] Welcome frame
   - [x] Game frame @Szaller99 
      - [x] Battleshipmegjelenítő @Ketszersult  
      - [x] Tile - basics @Szaller99
      - [x] Tile - Completed 
         - [x] GameTile @toratoraaa 
         - [x] LegendTile  @toratoraaa 
   - [x] End frame
- [x] Communication @Szaller99 
   - [x] tcp host
   - [x] tcp client

Egyéb feature-ok

- [x] Hajókat egymás mellé ne lehessen rakni @toratoraaa
